#pragma once
#include "gfx.h"

extern const VkDescriptorType uniform_type_to_vulkan_descriptor_type[UNIFORM_TYPE_MAX];
extern const UniformType uniform_type_from_vulkan_descriptor_type[VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT];
extern const VkPipelineStageFlags resource_usage_to_vulkan_pipeline_stage[RESOURCE_USAGE_MAX];
extern const VkAccessFlags resource_usage_to_vulkan_access_flags[RESOURCE_USAGE_MAX];
extern const VkImageLayout resource_usage_to_vulkan_image_layout[RESOURCE_USAGE_MAX];
extern const VkMemoryPropertyFlags memory_type_to_vulkan_memory_flags[MEMORY_TYPE_MAX];
extern const VkFormat pixel_format_to_vulkan_format[PIXEL_FORMAT_MAX];
extern const VkImageViewType image_type_to_vulkan_image_view_type[IMAGE_TYPE_MAX];

extern VkImageUsageFlags image_options_to_vulkan_image_usage_flags(ImageOptions opt);
extern VkBufferUsageFlags buffer_options_to_vulkan_buffer_usage_flags(BufferOptions options);
extern VkImageAspectFlags image_options_to_vulkan_aspect_flags(ImageOptions options);
extern VkSampleCountFlags image_options_to_vulkan_sample_count(VkPhysicalDeviceLimits limits, ImageOptions options);
extern uint32_t image_options_to_vulkan_layer_count(ImageOptions opt);
extern VkImageCreateFlags image_options_to_vulkan_image_flags(ImageOptions opt);
extern bool uniforms_to_vulkan_descriptor_bindings(Uniform *uniforms, uint32_t uniform_count, VkDescriptorSetLayoutBinding bindings[32], VkShaderStageFlagBits stages);

// EXTENSIONS
extern VKAPI_ATTR VkResult VKAPI_CALL STUB_vkCreateDebugUtilsMessenger(VkInstance i, const VkDebugUtilsMessengerCreateInfoEXT *c, const VkAllocationCallbacks *a, VkDebugUtilsMessengerEXT *m);
extern VKAPI_ATTR void VKAPI_CALL STUB_vkDestroyDebugUtilsMessenger(VkInstance i, VkDebugUtilsMessengerEXT m, const VkAllocationCallbacks *a);
extern VKAPI_ATTR VkResult VKAPI_CALL STUB_vkSetDebugUtilsObjectName(VkDevice d, const VkDebugUtilsObjectNameInfoEXT *n);
extern VKAPI_ATTR void VKAPI_CALL STUB_vkCmdBeginDebugUtilsLabel(VkCommandBuffer c, const VkDebugUtilsLabelEXT *l);
extern VKAPI_ATTR void VKAPI_CALL STUB_vkCmdEndDebugUtilsLabel(VkCommandBuffer c);

extern PFN_vkCreateDebugUtilsMessengerEXT vkCreateDebugUtilsMessenger;
extern PFN_vkDestroyDebugUtilsMessengerEXT vkDestroyDebugUtilsMessenger;
extern PFN_vkSetDebugUtilsObjectNameEXT vkSetDebugUtilsObjectName;
extern PFN_vkCmdBeginDebugUtilsLabelEXT vkCmdBeginDebugUtilsLabel;
extern PFN_vkCmdEndDebugUtilsLabelEXT vkCmdEndDebugUtilsLabel;
