#include "tables.h"
#include "gfx/gfx_types.h"

const VkDescriptorType uniform_type_to_vulkan_descriptor_type[UNIFORM_TYPE_MAX] = {
	[UNIFORM_TYPE_IMAGE] = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
	[UNIFORM_TYPE_STORAGE_IMAGE] = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
	[UNIFORM_TYPE_SAMPLER] = VK_DESCRIPTOR_TYPE_SAMPLER,
	[UNIFORM_TYPE_SAMPLER_WITH_IMAGE] = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
	[UNIFORM_TYPE_UNIFORM_BUFFER] = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
	[UNIFORM_TYPE_STORAGE_BUFFER] = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
	[UNIFORM_TYPE_UNIFORM_BUFFER_DYNAMIC] = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
	[UNIFORM_TYPE_STORAGE_BUFFER_DYNAMIC] = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC,
};

const UniformType uniform_type_from_vulkan_descriptor_type[VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT] = {
	[VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE] = UNIFORM_TYPE_IMAGE,
	[VK_DESCRIPTOR_TYPE_STORAGE_IMAGE] = UNIFORM_TYPE_STORAGE_IMAGE,
	[VK_DESCRIPTOR_TYPE_SAMPLER] = UNIFORM_TYPE_SAMPLER,
	[VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER] = UNIFORM_TYPE_SAMPLER_WITH_IMAGE,

	[VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER] = UNIFORM_TYPE_UNIFORM_BUFFER,
	[VK_DESCRIPTOR_TYPE_STORAGE_BUFFER] = UNIFORM_TYPE_STORAGE_BUFFER,

	[VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC] = UNIFORM_TYPE_UNIFORM_BUFFER_DYNAMIC,
	[VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC] = UNIFORM_TYPE_STORAGE_BUFFER_DYNAMIC,
};

const VkPipelineStageFlags resource_usage_to_vulkan_pipeline_stage[RESOURCE_USAGE_MAX] = {
	[RESOURCE_USAGE_UNDEFINED] = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,

	[RESOURCE_USAGE_TRANSFER_DST] = VK_PIPELINE_STAGE_TRANSFER_BIT,
	[RESOURCE_USAGE_TRANSFER_SRC] = VK_PIPELINE_STAGE_TRANSFER_BIT,

	[RESOURCE_USAGE_SHADER_READ] = VK_PIPELINE_STAGE_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
	[RESOURCE_USAGE_SHADER_WRITE] = VK_PIPELINE_STAGE_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,

	[RESOURCE_USAGE_VERTEX_BUFFER] = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,
	[RESOURCE_USAGE_INDEX_BUFFER] = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,

	[RESOURCE_USAGE_VERTEX_SHADER_READ] = VK_PIPELINE_STAGE_VERTEX_SHADER_BIT,
	[RESOURCE_USAGE_VERTEX_SHADER_WRITE] = VK_PIPELINE_STAGE_VERTEX_SHADER_BIT,

	[RESOURCE_USAGE_FRAGMENT_SHADER_READ] = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
	[RESOURCE_USAGE_FRAGMENT_SHADER_WRITE] = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,

	[RESOURCE_USAGE_COMPUTE_SHADER_READ] = VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
	[RESOURCE_USAGE_COMPUTE_SHADER_WRITE] = VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,

	[RESOURCE_USAGE_COLOR_ATTACHMENT] = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,

	[RESOURCE_USAGE_DEPTH_ATTACHMENT] = VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,

	[RESOURCE_USAGE_PRESENT] = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,
};

const VkAccessFlags resource_usage_to_vulkan_access_flags[RESOURCE_USAGE_MAX] = {
	[RESOURCE_USAGE_UNDEFINED] = 0,

	[RESOURCE_USAGE_TRANSFER_SRC] = VK_ACCESS_TRANSFER_READ_BIT,
	[RESOURCE_USAGE_TRANSFER_DST] = VK_ACCESS_TRANSFER_WRITE_BIT,

	[RESOURCE_USAGE_SHADER_READ] = VK_ACCESS_SHADER_READ_BIT,
	[RESOURCE_USAGE_VERTEX_SHADER_READ] = VK_ACCESS_SHADER_READ_BIT,
	[RESOURCE_USAGE_FRAGMENT_SHADER_READ] = VK_ACCESS_SHADER_READ_BIT,
	[RESOURCE_USAGE_COMPUTE_SHADER_READ] = VK_ACCESS_SHADER_READ_BIT,

	[RESOURCE_USAGE_SHADER_WRITE] = VK_ACCESS_SHADER_WRITE_BIT,
	[RESOURCE_USAGE_VERTEX_SHADER_WRITE] = VK_ACCESS_SHADER_WRITE_BIT,
	[RESOURCE_USAGE_FRAGMENT_SHADER_WRITE] = VK_ACCESS_SHADER_WRITE_BIT,
	[RESOURCE_USAGE_COMPUTE_SHADER_WRITE] = VK_ACCESS_SHADER_WRITE_BIT,

	[RESOURCE_USAGE_VERTEX_BUFFER] = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT,
	[RESOURCE_USAGE_INDEX_BUFFER] = VK_ACCESS_INDEX_READ_BIT,

	[RESOURCE_USAGE_COLOR_ATTACHMENT] = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,

	[RESOURCE_USAGE_DEPTH_ATTACHMENT] = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,

	[RESOURCE_USAGE_PRESENT] = 0,
};
const VkImageLayout resource_usage_to_vulkan_image_layout[RESOURCE_USAGE_MAX] = {
	[RESOURCE_USAGE_UNDEFINED] = VK_IMAGE_LAYOUT_UNDEFINED,

	[RESOURCE_USAGE_TRANSFER_SRC] = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
	[RESOURCE_USAGE_SHADER_READ] = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
	[RESOURCE_USAGE_VERTEX_SHADER_READ] = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
	[RESOURCE_USAGE_FRAGMENT_SHADER_READ] = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
	[RESOURCE_USAGE_COMPUTE_SHADER_READ] = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
	[RESOURCE_USAGE_VERTEX_BUFFER] = VK_IMAGE_LAYOUT_UNDEFINED,
	[RESOURCE_USAGE_INDEX_BUFFER] = VK_IMAGE_LAYOUT_UNDEFINED,
	[RESOURCE_USAGE_PRESENT] = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,

	[RESOURCE_USAGE_TRANSFER_DST] = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
	[RESOURCE_USAGE_SHADER_WRITE] = VK_IMAGE_LAYOUT_GENERAL,
	[RESOURCE_USAGE_VERTEX_SHADER_WRITE] = VK_IMAGE_LAYOUT_GENERAL,
	[RESOURCE_USAGE_FRAGMENT_SHADER_WRITE] = VK_IMAGE_LAYOUT_GENERAL,
	[RESOURCE_USAGE_COMPUTE_SHADER_WRITE] = VK_IMAGE_LAYOUT_GENERAL,
	[RESOURCE_USAGE_COLOR_ATTACHMENT] = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
	[RESOURCE_USAGE_DEPTH_ATTACHMENT] = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
};

const VkMemoryPropertyFlags memory_type_to_vulkan_memory_flags[MEMORY_TYPE_MAX] = {
	[MEMORY_TYPE_GPU] = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
	[MEMORY_TYPE_CPU] = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
};

const VkFormat pixel_format_to_vulkan_format[PIXEL_FORMAT_MAX] = {
	[PIXEL_FORMAT_RGBA8_UNORM] = VK_FORMAT_R8G8B8A8_UNORM,
	[PIXEL_FORMAT_RGBA8_SRGB] = VK_FORMAT_R8G8B8A8_SRGB,

	[PIXEL_FORMAT_BGRA8_UNORM] = VK_FORMAT_B8G8R8A8_UNORM,
	[PIXEL_FORMAT_BGRA8_SRGB] = VK_FORMAT_B8G8R8A8_SRGB,

	[PIXEL_FORMAT_RGBA16_FLOAT] = VK_FORMAT_R16G16B16A16_SFLOAT,
	[PIXEL_FORMAT_R32_FLOAT] = VK_FORMAT_R32_SFLOAT,
	[PIXEL_FORMAT_DEPTH] = VK_FORMAT_D32_SFLOAT,
	[PIXEL_FORMAT_DEPTHSTENCIL] = VK_FORMAT_D24_UNORM_S8_UINT,
};

const VkImageViewType image_type_to_vulkan_image_view_type[IMAGE_TYPE_MAX] = {
	[IMAGE_TYPE_2D] = VK_IMAGE_VIEW_TYPE_2D,
	[IMAGE_TYPE_3D] = VK_IMAGE_VIEW_TYPE_3D,
	[IMAGE_TYPE_CUBE] = VK_IMAGE_VIEW_TYPE_CUBE,

};

VkImageUsageFlags image_options_to_vulkan_image_usage_flags(ImageOptions opt) {
	VkImageUsageFlags result = 0;
	if (has_flag(opt.usage, IMAGE_USAGE_RENDER)) {
		if (pixel_format_is_depth(opt.format))
			result |= VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
		else
			result |= VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
	}

	if (has_flag(opt.usage, IMAGE_USAGE_SAMPLE))
		result |= VK_IMAGE_USAGE_SAMPLED_BIT;

	if (has_flag(opt.usage, IMAGE_USAGE_STORAGE))
		result |= VK_IMAGE_USAGE_STORAGE_BIT;

	if (has_flag(opt.usage, IMAGE_USAGE_TRANSFER))
		result |= VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;

	if (result == 0) { // default
		result |= VK_IMAGE_USAGE_SAMPLED_BIT;
		result |= VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
	}

	if (opt.pixels && (result & VK_IMAGE_USAGE_TRANSFER_DST_BIT) == 0)
		result |= VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;

	return result;
}

VkImageAspectFlags image_options_to_vulkan_aspect_flags(ImageOptions options) {
	if (pixel_format_is_depth_stencil(options.format))
		return VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT;
	if (pixel_format_is_depth(options.format))
		return VK_IMAGE_ASPECT_DEPTH_BIT;

	return VK_IMAGE_ASPECT_COLOR_BIT;
}

VkSampleCountFlags image_options_to_vulkan_sample_count(VkPhysicalDeviceLimits limits, ImageOptions options) {
	VkSampleCountFlags result = MAX((VkSampleCountFlags)options.sample, VK_SAMPLE_COUNT_1_BIT);

	if (has_flag(options.usage, IMAGE_USAGE_SAMPLE)) {
		if (pixel_format_is_depth(options.format)) {
			result = MIN(result, limits.sampledImageDepthSampleCounts);
			result = MIN(result, limits.sampledImageStencilSampleCounts);
		} else {
			result = MIN(result, limits.sampledImageColorSampleCounts);
		}
	}

	if (has_flag(options.usage, IMAGE_USAGE_RENDER)) {
		if (pixel_format_is_depth(options.format)) {
			result = MIN(result, limits.framebufferDepthSampleCounts);
			result = MIN(result, limits.framebufferStencilSampleCounts);
		} else
			result = MIN(result, limits.framebufferColorSampleCounts);
	}

	if (has_flag(options.usage, IMAGE_USAGE_STORAGE))
		result = MIN(result, limits.storageImageSampleCounts);

	return result;
}

inline uint32_t image_options_to_vulkan_layer_count(ImageOptions opt) {
	return opt.slice_count ? opt.slice_count : opt.type == IMAGE_TYPE_CUBE ? 6
																		   : 1;
}

inline VkBufferUsageFlags buffer_options_to_vulkan_buffer_usage_flags(BufferOptions options) {
	VkBufferUsageFlags result = 0;
	if (has_flag(options.usage, BUFFER_USAGE_UNIFORM))
		result |= VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT | VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT;
	if (has_flag(options.usage, BUFFER_USAGE_STORAGE))
		result |= VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT;
	if (has_flag(options.usage, BUFFER_USAGE_VERTEX))
		result |= VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
	if (has_flag(options.usage, BUFFER_USAGE_INDEX))
		result |= VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
	if (has_flag(options.usage, BUFFER_USAGE_TRANSFER) || options.data)
		result |= VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT;

	return result;
}
inline VkImageCreateFlags image_options_to_vulkan_image_flags(ImageOptions opt) {
	VkImageCreateFlags result = 0;

	if (opt.type == IMAGE_TYPE_CUBE)
		result = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;

	return result;
}

inline bool uniforms_to_vulkan_descriptor_bindings(Uniform *uniforms, uint32_t uniform_count, VkDescriptorSetLayoutBinding bindings[32], VkShaderStageFlagBits stages) {
	bool ok = uniforms && uniform_count > 0 && bindings;

	if (ok) {
		for (uint32_t index = 0; index < uniform_count; ++index) {
			Uniform *uniform = &uniforms[index];

			bindings[index] = (VkDescriptorSetLayoutBinding){
				.binding = uniform->binding,
				.descriptorCount = uniform->count,
				.descriptorType = uniform_type_to_vulkan_descriptor_type[uniform->type],
				.stageFlags = stages
			};
		}
	}

	return ok;
}

VKAPI_ATTR VkResult VKAPI_CALL STUB_vkCreateDebugUtilsMessenger(VkInstance i, const VkDebugUtilsMessengerCreateInfoEXT *c, const VkAllocationCallbacks *a, VkDebugUtilsMessengerEXT *m) { return VK_ERROR_EXTENSION_NOT_PRESENT; }
VKAPI_ATTR void VKAPI_CALL STUB_vkDestroyDebugUtilsMessenger(VkInstance i, VkDebugUtilsMessengerEXT m, const VkAllocationCallbacks *a) {}
VKAPI_ATTR VkResult VKAPI_CALL STUB_vkSetDebugUtilsObjectName(VkDevice d, const VkDebugUtilsObjectNameInfoEXT *n) { return VK_SUCCESS; }
VKAPI_ATTR void VKAPI_CALL STUB_vkCmdBeginDebugUtilsLabel(VkCommandBuffer c, const VkDebugUtilsLabelEXT *l) {}
VKAPI_ATTR void VKAPI_CALL STUB_vkCmdEndDebugUtilsLabel(VkCommandBuffer c) {}
