#version 460
#pragma shader_stage(compute)

#extension GL_EXT_buffer_reference: require

// size of a workgroup for compute
layout (local_size_x = 256, local_size_y = 1) in;

struct SkinningData {
    ivec4 id;
    vec4 weight;
};

struct VertexData {
    vec4 position; 
    vec4 normal;
    vec2 uv;
    vec4 tangent;
};

layout(buffer_reference, std430) readonly buffer VertexBuffer {
    VertexData vertex_data[];
};

layout(buffer_reference, std430) readonly buffer SkinningBuffer {
    SkinningData skinning_data[];
};

layout(buffer_reference, std430) readonly buffer SkinningMatrices {
    mat4 matrices[];
};

layout(push_constant) uniform ConstantBlock {
    uint vertex_count;
    SkinningMatrices transform;
    VertexBuffer input_buffer;
    SkinningBuffer skinning_buffer;
    VertexBuffer output_buffer;
};

void main() {
    uint vertex_index = gl_GlobalInvocationID.x;
    if (vertex_index >= vertex_count) return;

    SkinningData sd = skinning_buffer.skinning_data[vertex_index]; 
    vec4 pos = vec4(input_buffer.vertex_data[vertex_index].position.xyz, 1.0f);

    vec4 skinned = 
        sd.weight[0] * transform.matrices[sd.id[0]] * pos + 
        sd.weight[1] * transform.matrices[sd.id[1]] * pos + 
        sd.weight[2] * transform.matrices[sd.id[2]] * pos + 
        sd.weight[3] * transform.matrices[sd.id[3]] * pos;

    output_buffer.vertex_data[vertex_index] = input_buffer.vertex_data[vertex_index];
    output_buffer.vertex_data[vertex_index].position = vec4(skinned.xyz, input_buffer.vertex_data[vertex_index].position.w);
}
