#include "meta_generated.h"
#include "components.h"

Type type_introspection[TYPE_MAX] = {
    [TYPE_float32x2] = {
        .type = TYPE_float32x2,
        .name = "float32x2",
        .alignment = alignof(float32x2),
        .size = sizeof(float32x2),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x2, x),
                .size = sizeof(((float32x2*)0)->x),
                .stride = sizeof(float),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x2, y),
                .size = sizeof(((float32x2*)0)->y),
                .stride = sizeof(float),
                .count = 1,
            },
        },
    },
    [TYPE_float32x3] = {
        .type = TYPE_float32x3,
        .name = "float32x3",
        .alignment = alignof(float32x3),
        .size = sizeof(float32x3),
        .member_count = 3,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x3, x),
                .size = sizeof(((float32x3*)0)->x),
                .stride = sizeof(float),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x3, y),
                .size = sizeof(((float32x3*)0)->y),
                .stride = sizeof(float),
                .count = 1,
            },
            [2] = {
                .type = TYPE_float,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x3, z),
                .size = sizeof(((float32x3*)0)->z),
                .stride = sizeof(float),
                .count = 1,
            },
        },
    },
    [TYPE_float32x4] = {
        .type = TYPE_float32x4,
        .name = "float32x4",
        .alignment = alignof(float32x4),
        .size = sizeof(float32x4),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x4, x),
                .size = sizeof(((float32x4*)0)->x),
                .stride = sizeof(float),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x4, y),
                .size = sizeof(((float32x4*)0)->y),
                .stride = sizeof(float),
                .count = 1,
            },
            [2] = {
                .type = TYPE_float,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x4, z),
                .size = sizeof(((float32x4*)0)->z),
                .stride = sizeof(float),
                .count = 1,
            },
            [3] = {
                .type = TYPE_float,
                .field_name = "w",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float32x4, w),
                .size = sizeof(((float32x4*)0)->w),
                .stride = sizeof(float),
                .count = 1,
            },
        },
    },
    [TYPE_float64x2] = {
        .type = TYPE_float64x2,
        .name = "float64x2",
        .alignment = alignof(float64x2),
        .size = sizeof(float64x2),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float64,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x2, x),
                .size = sizeof(((float64x2*)0)->x),
                .stride = sizeof(float64),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float64,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x2, y),
                .size = sizeof(((float64x2*)0)->y),
                .stride = sizeof(float64),
                .count = 1,
            },
        },
    },
    [TYPE_float64x3] = {
        .type = TYPE_float64x3,
        .name = "float64x3",
        .alignment = alignof(float64x3),
        .size = sizeof(float64x3),
        .member_count = 3,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float64,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x3, x),
                .size = sizeof(((float64x3*)0)->x),
                .stride = sizeof(float64),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float64,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x3, y),
                .size = sizeof(((float64x3*)0)->y),
                .stride = sizeof(float64),
                .count = 1,
            },
            [2] = {
                .type = TYPE_float64,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x3, z),
                .size = sizeof(((float64x3*)0)->z),
                .stride = sizeof(float64),
                .count = 1,
            },
        },
    },
    [TYPE_float64x4] = {
        .type = TYPE_float64x4,
        .name = "float64x4",
        .alignment = alignof(float64x4),
        .size = sizeof(float64x4),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float64,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x4, x),
                .size = sizeof(((float64x4*)0)->x),
                .stride = sizeof(float64),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float64,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x4, y),
                .size = sizeof(((float64x4*)0)->y),
                .stride = sizeof(float64),
                .count = 1,
            },
            [2] = {
                .type = TYPE_float64,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x4, z),
                .size = sizeof(((float64x4*)0)->z),
                .stride = sizeof(float64),
                .count = 1,
            },
            [3] = {
                .type = TYPE_float64,
                .field_name = "w",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(float64x4, w),
                .size = sizeof(((float64x4*)0)->w),
                .stride = sizeof(float64),
                .count = 1,
            },
        },
    },
    [TYPE_uint32x2] = {
        .type = TYPE_uint32x2,
        .name = "uint32x2",
        .alignment = alignof(uint32x2),
        .size = sizeof(uint32x2),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_uint32,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x2, x),
                .size = sizeof(((uint32x2*)0)->x),
                .stride = sizeof(uint32),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint32,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x2, y),
                .size = sizeof(((uint32x2*)0)->y),
                .stride = sizeof(uint32),
                .count = 1,
            },
        },
    },
    [TYPE_uint32x3] = {
        .type = TYPE_uint32x3,
        .name = "uint32x3",
        .alignment = alignof(uint32x3),
        .size = sizeof(uint32x3),
        .member_count = 3,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_uint32,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x3, x),
                .size = sizeof(((uint32x3*)0)->x),
                .stride = sizeof(uint32),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint32,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x3, y),
                .size = sizeof(((uint32x3*)0)->y),
                .stride = sizeof(uint32),
                .count = 1,
            },
            [2] = {
                .type = TYPE_uint32,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x3, z),
                .size = sizeof(((uint32x3*)0)->z),
                .stride = sizeof(uint32),
                .count = 1,
            },
        },
    },
    [TYPE_uint32x4] = {
        .type = TYPE_uint32x4,
        .name = "uint32x4",
        .alignment = alignof(uint32x4),
        .size = sizeof(uint32x4),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_uint32,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x4, x),
                .size = sizeof(((uint32x4*)0)->x),
                .stride = sizeof(uint32),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint32,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x4, y),
                .size = sizeof(((uint32x4*)0)->y),
                .stride = sizeof(uint32),
                .count = 1,
            },
            [2] = {
                .type = TYPE_uint32,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x4, z),
                .size = sizeof(((uint32x4*)0)->z),
                .stride = sizeof(uint32),
                .count = 1,
            },
            [3] = {
                .type = TYPE_uint32,
                .field_name = "w",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint32x4, w),
                .size = sizeof(((uint32x4*)0)->w),
                .stride = sizeof(uint32),
                .count = 1,
            },
        },
    },
    [TYPE_uint64x2] = {
        .type = TYPE_uint64x2,
        .name = "uint64x2",
        .alignment = alignof(uint64x2),
        .size = sizeof(uint64x2),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_uint64,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x2, x),
                .size = sizeof(((uint64x2*)0)->x),
                .stride = sizeof(uint64),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint64,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x2, y),
                .size = sizeof(((uint64x2*)0)->y),
                .stride = sizeof(uint64),
                .count = 1,
            },
        },
    },
    [TYPE_uint64x3] = {
        .type = TYPE_uint64x3,
        .name = "uint64x3",
        .alignment = alignof(uint64x3),
        .size = sizeof(uint64x3),
        .member_count = 3,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_uint64,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x3, x),
                .size = sizeof(((uint64x3*)0)->x),
                .stride = sizeof(uint64),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint64,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x3, y),
                .size = sizeof(((uint64x3*)0)->y),
                .stride = sizeof(uint64),
                .count = 1,
            },
            [2] = {
                .type = TYPE_uint64,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x3, z),
                .size = sizeof(((uint64x3*)0)->z),
                .stride = sizeof(uint64),
                .count = 1,
            },
        },
    },
    [TYPE_uint64x4] = {
        .type = TYPE_uint64x4,
        .name = "uint64x4",
        .alignment = alignof(uint64x4),
        .size = sizeof(uint64x4),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_uint64,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x4, x),
                .size = sizeof(((uint64x4*)0)->x),
                .stride = sizeof(uint64),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint64,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x4, y),
                .size = sizeof(((uint64x4*)0)->y),
                .stride = sizeof(uint64),
                .count = 1,
            },
            [2] = {
                .type = TYPE_uint64,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x4, z),
                .size = sizeof(((uint64x4*)0)->z),
                .stride = sizeof(uint64),
                .count = 1,
            },
            [3] = {
                .type = TYPE_uint64,
                .field_name = "w",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(uint64x4, w),
                .size = sizeof(((uint64x4*)0)->w),
                .stride = sizeof(uint64),
                .count = 1,
            },
        },
    },
    [TYPE_int32x2] = {
        .type = TYPE_int32x2,
        .name = "int32x2",
        .alignment = alignof(int32x2),
        .size = sizeof(int32x2),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_int32,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x2, x),
                .size = sizeof(((int32x2*)0)->x),
                .stride = sizeof(int32),
                .count = 1,
            },
            [1] = {
                .type = TYPE_int32,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x2, y),
                .size = sizeof(((int32x2*)0)->y),
                .stride = sizeof(int32),
                .count = 1,
            },
        },
    },
    [TYPE_int32x3] = {
        .type = TYPE_int32x3,
        .name = "int32x3",
        .alignment = alignof(int32x3),
        .size = sizeof(int32x3),
        .member_count = 3,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_int32,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x3, x),
                .size = sizeof(((int32x3*)0)->x),
                .stride = sizeof(int32),
                .count = 1,
            },
            [1] = {
                .type = TYPE_int32,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x3, y),
                .size = sizeof(((int32x3*)0)->y),
                .stride = sizeof(int32),
                .count = 1,
            },
            [2] = {
                .type = TYPE_int32,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x3, z),
                .size = sizeof(((int32x3*)0)->z),
                .stride = sizeof(int32),
                .count = 1,
            },
        },
    },
    [TYPE_int32x4] = {
        .type = TYPE_int32x4,
        .name = "int32x4",
        .alignment = alignof(int32x4),
        .size = sizeof(int32x4),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_int32,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x4, x),
                .size = sizeof(((int32x4*)0)->x),
                .stride = sizeof(int32),
                .count = 1,
            },
            [1] = {
                .type = TYPE_int32,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x4, y),
                .size = sizeof(((int32x4*)0)->y),
                .stride = sizeof(int32),
                .count = 1,
            },
            [2] = {
                .type = TYPE_int32,
                .field_name = "z",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x4, z),
                .size = sizeof(((int32x4*)0)->z),
                .stride = sizeof(int32),
                .count = 1,
            },
            [3] = {
                .type = TYPE_int32,
                .field_name = "w",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(int32x4, w),
                .size = sizeof(((int32x4*)0)->w),
                .stride = sizeof(int32),
                .count = 1,
            },
        },
    },
    [TYPE_Interval] = {
        .type = TYPE_Interval,
        .name = "Interval",
        .alignment = alignof(Interval),
        .size = sizeof(Interval),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float,
                .field_name = "min",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Interval, min),
                .size = sizeof(((Interval*)0)->min),
                .stride = sizeof(float),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float,
                .field_name = "max",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Interval, max),
                .size = sizeof(((Interval*)0)->max),
                .stride = sizeof(float),
                .count = 1,
            },
        },
    },
    [TYPE_Interval2] = {
        .type = TYPE_Interval2,
        .name = "Interval2",
        .alignment = alignof(Interval2),
        .size = sizeof(Interval2),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float32x2,
                .field_name = "min",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Interval2, min),
                .size = sizeof(((Interval2*)0)->min),
                .stride = sizeof(float32x2),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float32x2,
                .field_name = "max",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Interval2, max),
                .size = sizeof(((Interval2*)0)->max),
                .stride = sizeof(float32x2),
                .count = 1,
            },
        },
    },
    [TYPE_Interval3] = {
        .type = TYPE_Interval3,
        .name = "Interval3",
        .alignment = alignof(Interval3),
        .size = sizeof(Interval3),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float32x3,
                .field_name = "min",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Interval3, min),
                .size = sizeof(((Interval3*)0)->min),
                .stride = sizeof(float32x3),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float32x3,
                .field_name = "max",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Interval3, max),
                .size = sizeof(((Interval3*)0)->max),
                .stride = sizeof(float32x3),
                .count = 1,
            },
        },
    },
    [TYPE_Color] = {
        .type = TYPE_Color,
        .name = "Color",
        .alignment = alignof(Color),
        .size = sizeof(Color),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_uint8_t,
                .field_name = "r",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Color, r),
                .size = sizeof(((Color*)0)->r),
                .stride = sizeof(uint8_t),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint8_t,
                .field_name = "g",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Color, g),
                .size = sizeof(((Color*)0)->g),
                .stride = sizeof(uint8_t),
                .count = 1,
            },
            [2] = {
                .type = TYPE_uint8_t,
                .field_name = "b",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Color, b),
                .size = sizeof(((Color*)0)->b),
                .stride = sizeof(uint8_t),
                .count = 1,
            },
            [3] = {
                .type = TYPE_uint8_t,
                .field_name = "a",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Color, a),
                .size = sizeof(((Color*)0)->a),
                .stride = sizeof(uint8_t),
                .count = 1,
            },
        },
    },
    [TYPE_Buffer] = {
        .type = TYPE_Buffer,
        .name = "Buffer",
        .alignment = alignof(Buffer),
        .size = sizeof(Buffer),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_size_t,
                .field_name = "size",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Buffer, size),
                .size = sizeof(((Buffer*)0)->size),
                .stride = sizeof(size_t),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint8_t,
                .field_name = "memory",
                .flags = TYPE_MEMBER_FLAG_POINTER,
                .indirection = 1,
                .offset = offsetof(Buffer, memory),
                .size = sizeof(((Buffer*)0)->memory),
                .stride = sizeof(uint8_t),
                .count = 1,
            },
        },
    },
    [TYPE_float4x4] = {
        .type = TYPE_float4x4,
        .name = "float4x4",
        .alignment = alignof(float4x4),
        .size = sizeof(float4x4),
        .member_count = 1,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float,
                .field_name = "elements",
                .flags = TYPE_MEMBER_FLAG_ARRAY,
                .indirection = 0,
                .offset = offsetof(float4x4, elements),
                .size = sizeof(((float4x4*)0)->elements),
                .stride = sizeof(float),
                .count = 4*4,
            },
        },
    },
    [TYPE_Ray3] = {
        .type = TYPE_Ray3,
        .name = "Ray3",
        .alignment = alignof(Ray3),
        .size = sizeof(Ray3),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float3,
                .field_name = "origin",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Ray3, origin),
                .size = sizeof(((Ray3*)0)->origin),
                .stride = sizeof(float3),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float3,
                .field_name = "direction",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Ray3, direction),
                .size = sizeof(((Ray3*)0)->direction),
                .stride = sizeof(float3),
                .count = 1,
            },
        },
    },
    [TYPE_Raycast3Result] = {
        .type = TYPE_Raycast3Result,
        .name = "Raycast3Result",
        .alignment = alignof(Raycast3Result),
        .size = sizeof(Raycast3Result),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_bool,
                .field_name = "hit",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Raycast3Result, hit),
                .size = sizeof(((Raycast3Result*)0)->hit),
                .stride = sizeof(bool),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float,
                .field_name = "t",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Raycast3Result, t),
                .size = sizeof(((Raycast3Result*)0)->t),
                .stride = sizeof(float),
                .count = 1,
            },
            [2] = {
                .type = TYPE_float3,
                .field_name = "normal",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Raycast3Result, normal),
                .size = sizeof(((Raycast3Result*)0)->normal),
                .stride = sizeof(float3),
                .count = 1,
            },
            [3] = {
                .type = TYPE_float3,
                .field_name = "point",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Raycast3Result, point),
                .size = sizeof(((Raycast3Result*)0)->point),
                .stride = sizeof(float3),
                .count = 1,
            },
        },
    },
    [TYPE_Rectangle] = {
        .type = TYPE_Rectangle,
        .name = "Rectangle",
        .alignment = alignof(Rectangle),
        .size = sizeof(Rectangle),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float,
                .field_name = "x",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Rectangle, x),
                .size = sizeof(((Rectangle*)0)->x),
                .stride = sizeof(float),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float,
                .field_name = "y",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Rectangle, y),
                .size = sizeof(((Rectangle*)0)->y),
                .stride = sizeof(float),
                .count = 1,
            },
            [2] = {
                .type = TYPE_float,
                .field_name = "width",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Rectangle, width),
                .size = sizeof(((Rectangle*)0)->width),
                .stride = sizeof(float),
                .count = 1,
            },
            [3] = {
                .type = TYPE_float,
                .field_name = "height",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Rectangle, height),
                .size = sizeof(((Rectangle*)0)->height),
                .stride = sizeof(float),
                .count = 1,
            },
        },
    },
    [TYPE_Transform3] = {
        .type = TYPE_Transform3,
        .name = "Transform3",
        .alignment = alignof(Transform3),
        .size = sizeof(Transform3),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float3,
                .field_name = "position",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Transform3, position),
                .size = sizeof(((Transform3*)0)->position),
                .stride = sizeof(float3),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float3,
                .field_name = "rotation",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Transform3, rotation),
                .size = sizeof(((Transform3*)0)->rotation),
                .stride = sizeof(float3),
                .count = 1,
            },
            [2] = {
                .type = TYPE_float3,
                .field_name = "scale",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Transform3, scale),
                .size = sizeof(((Transform3*)0)->scale),
                .stride = sizeof(float3),
                .count = 1,
            },
            [3] = {
                .type = TYPE_float4x4,
                .field_name = "world_matrix",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(Transform3, world_matrix),
                .size = sizeof(((Transform3*)0)->world_matrix),
                .stride = sizeof(float4x4),
                .count = 1,
            },
        },
    },
    [TYPE_MeshComponent] = {
        .type = TYPE_MeshComponent,
        .name = "MeshComponent",
        .alignment = alignof(MeshComponent),
        .size = sizeof(MeshComponent),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_UUID,
                .field_name = "group_id",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(MeshComponent, group_id),
                .size = sizeof(((MeshComponent*)0)->group_id),
                .stride = sizeof(UUID),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint32_t,
                .field_name = "mesh_group_index",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(MeshComponent, mesh_group_index),
                .size = sizeof(((MeshComponent*)0)->mesh_group_index),
                .stride = sizeof(uint32_t),
                .count = 1,
            },
        },
    },
    [TYPE_ColliderComponent] = {
        .type = TYPE_ColliderComponent,
        .name = "ColliderComponent",
        .alignment = alignof(ColliderComponent),
        .size = sizeof(ColliderComponent),
        .member_count = 3,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_float3,
                .field_name = "aabb.center",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(ColliderComponent, aabb.center),
                .size = sizeof(((ColliderComponent*)0)->aabb.center),
                .stride = sizeof(float3),
                .count = 1,
            },
            [1] = {
                .type = TYPE_float3,
                .field_name = "aabb.extent",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(ColliderComponent, aabb.extent),
                .size = sizeof(((ColliderComponent*)0)->aabb.extent),
                .stride = sizeof(float3),
                .count = 1,
            },
        },
    },
    [TYPE_HierarchyComponent] = {
        .type = TYPE_HierarchyComponent,
        .name = "HierarchyComponent",
        .alignment = alignof(HierarchyComponent),
        .size = sizeof(HierarchyComponent),
        .member_count = 4,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_Entity,
                .field_name = "parent",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(HierarchyComponent, parent),
                .size = sizeof(((HierarchyComponent*)0)->parent),
                .stride = sizeof(Entity),
                .count = 1,
            },
            [1] = {
                .type = TYPE_Entity,
                .field_name = "first_child",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(HierarchyComponent, first_child),
                .size = sizeof(((HierarchyComponent*)0)->first_child),
                .stride = sizeof(Entity),
                .count = 1,
            },
            [2] = {
                .type = TYPE_Entity,
                .field_name = "next_sibling",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(HierarchyComponent, next_sibling),
                .size = sizeof(((HierarchyComponent*)0)->next_sibling),
                .stride = sizeof(Entity),
                .count = 1,
            },
            [3] = {
                .type = TYPE_Entity,
                .field_name = "prev_sibling",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(HierarchyComponent, prev_sibling),
                .size = sizeof(((HierarchyComponent*)0)->prev_sibling),
                .stride = sizeof(Entity),
                .count = 1,
            },
        },
    },
    [TYPE_InventorySlot] = {
        .type = TYPE_InventorySlot,
        .name = "InventorySlot",
        .alignment = alignof(InventorySlot),
        .size = sizeof(InventorySlot),
        .member_count = 2,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_uint32_t,
                .field_name = "item_index",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(InventorySlot, item_index),
                .size = sizeof(((InventorySlot*)0)->item_index),
                .stride = sizeof(uint32_t),
                .count = 1,
            },
            [1] = {
                .type = TYPE_uint8_t,
                .field_name = "quantity",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(InventorySlot, quantity),
                .size = sizeof(((InventorySlot*)0)->quantity),
                .stride = sizeof(uint8_t),
                .count = 1,
            },
        },
    },
    [TYPE_InventoryComponent] = {
        .type = TYPE_InventoryComponent,
        .name = "InventoryComponent",
        .alignment = alignof(InventoryComponent),
        .size = sizeof(InventoryComponent),
        .member_count = 3,
        .members = (TypeMember[]) {
            [0] = {
                .type = TYPE_InventorySlot,
                .field_name = "slots",
                .flags = TYPE_MEMBER_FLAG_ARRAY,
                .indirection = 0,
                .offset = offsetof(InventoryComponent, slots),
                .size = sizeof(((InventoryComponent*)0)->slots),
                .stride = sizeof(InventorySlot),
                .count = MAX_INVENTORY_SLOTS,
            },
            [1] = {
                .type = TYPE_InventorySlot,
                .field_name = "active_item",
                .flags = TYPE_MEMBER_FLAG_POINTER,
                .indirection = 1,
                .offset = offsetof(InventoryComponent, active_item),
                .size = sizeof(((InventoryComponent*)0)->active_item),
                .stride = sizeof(InventorySlot),
                .count = 1,
            },
            [2] = {
                .type = TYPE_uint32_t,
                .field_name = "capacity",
                .flags = 0,
                .indirection = 0,
                .offset = offsetof(InventoryComponent, capacity),
                .size = sizeof(((InventoryComponent*)0)->capacity),
                .stride = sizeof(uint32_t),
                .count = 1,
            },
        },
    },
};
