#pragma once

typedef enum {
	PIXEL_FORMAT_RGBA8_UNORM,
	PIXEL_FORMAT_RGBA8_SRGB,
	PIXEL_FORMAT_RGBA16_FLOAT,
	PIXEL_FORMAT_R32_FLOAT,
	PIXEL_FORMAT_D32_FLOAT,
	PIXEL_FORMAT_D24_UNORM_S8_UINT,
} PixelFormat;

typedef enum {
	IMAGE_USAGE_SAMPLE = 0x1,
	IMAGE_USAGE_RENDER = 0x2,
	IMAGE_USAGE_STORAGE = 0x4,
	IMAGE_USAGE_TRANSFER = 0x8
} ImageUsageFlags;

typedef enum {
	BUFFER_USAGE_VERTEX = 0x1,
	BUFFER_USAGE_INDEX = 0x2,
	BUFFER_USAGE_UNIFORM = 0x4,
	BUFFER_USAGE_STORAGE = 0x8,
	BUFFER_USAGE_TRANSFER = 0x10
} BufferUsage;

typedef enum {
	BUFFER_MEMORY_LOCAL,
	BUFFER_MEMORY_SHARED,
} BufferMemory;

typedef enum {
	SHADER_STAGE_VERTEX,
	SHADER_STAGE_FRAGMENT,
	SHADER_STAGE_COMPUTE,

	SHADER_STAGE_COUNT,
} ShaderStage;
